### ISSUE TITLE
What's the status of this portage?

### ISSUE THREAD

**Issue by Shumen** [Dexterp37/GPUImage#1]
Have those ported filters been tested to work correctly? Thank you in advance.

**Comment by Dexterp37** [comment]
Hi, sorry for the late reply, but somehow github didn't mail me about the issue :) The ported filters have been lightly tested and work on PC using OpenGLES emulation.

**Comment by Shumen** [comment]
Great, thank you for your reply, I would like to pick this cool project up, and consummate it. Do you pay your effort on it recently? I wish someone other work with me together.

**Comment by Shumen** [comment]
I'm working on it a few days ago, but just at the beginning.

**Comment by Dexterp37** [comment]
Sure, feel free to contribute! I had no time to update it recently, but I will be working on it in the following weeks. Feel free to share your opinion and comments.

**Comment by asloobq** [comment]
> The ported filters have been lightly tested and work on PC using OpenGLES emulation.

How did you set up the OpenGLES emulation? Did you use an Android project and the official emulators available at [Android Developers](http://developer.android.com/) ?

**Comment by Dexterp37** [comment]
I've been using Angle: you can download it from here https://code.google.com/p/angleproject/
