### ISSUE TITLE
How to integrate with FreeImage?

### ISSUE THREAD

**Issue by asloobq** [Dexterp37/GPUImage#3]
Some of the code references the FreeImage library. How do I integrate GPUImage with FreeImage library? I have downloaded the FreeImage source and placed it next to the GPUImage directory. 
Here is a part of my android make file-

```
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../Classes     \
$(LOCAL_PATH)/../../libs/Box2d  \
$(LOCAL_PATH)/../../libs/GPUImage  \
$(LOCAL_PATH)/../../libs/FreeImage

LOCAL_WHOLE_STATIC_LIBRARIES := cocos2dx_static cocosdenshion_static cocos_extension_static box2d_static gpuimage_static freeimage_static

include $(BUILD_SHARED_LIBRARY)

$(call import-module,CocosDenshion/android) \
$(call import-module,cocos2dx) \
$(call import-module,extensions) \
$(call import-module,Box2D) \
$(call import-module,GPUImage) \
$(call import-module,FreeImage)
```

**Comment by Dexterp37** [comment]
You need to compile the FreeImage library and link it against your Android project

**Comment by asloobq** [comment]
Ok I have compiled a static library separately. I've got a "libfreeimage.a", how did I link it to GPUImage. Any pointers on this ?

**Comment by Dexterp37** [comment]
Use CMake to find the libfreeimage file
